## Alexandre Theophile Vandermonde-Function so that columns of output matrix are increasing powers of input vector

## Solution:
* Write a method vandermonde_matrix which takes three argument, numpy array,  N as number of columns, boolean increasing, if false powers are taken for the vector in the order N-1 to 0, if true, powers are taken for the vectory in the order 0 to N -1
* In the method range is determined (N-1 to 0) or (0 to N-1) based on increasing.
* Initialize output_matrix an empty array
* Iterate over the range, for each iteration, take the vector element to power of iteration value and concate the resultant vector to output vector
* Reshape output_matrix using N and input_vector size and transpose the matrix so that resulting matrix has dimensions ((Number of elements in input x N)






In [51]:
import numpy as np

# Function vandermonde_matrix hich takes three argument, numpy array,  N as number of columns,
# boolean increasing, if false powers are taken for the vector in the order N-1 to 0, if true,
#powers are taken for the vectory in the order 0 to N -1
def vandermonde_matrix(input, N=None, increasing=False):
    input_vector = input
    # If N is None, initialize N to shape of input_vector
    if N is None:
        N = input_vector.shape[0]
    r = None
    
    # if incresing is False, assign r descreasing order from N-1 to 0
    # if incresing is True, assign r descreasing order from 0 to N-1
    if increasing == False :
        r = range(N-1, -1, -1)
    else:
        r = range(0, N)
    
    # Initialize output_mtrix
    output_matrix = np.array([])
    
    # For each in in  r, calculate the input_vector to the power i and concatenate
    # to the output_matirx
    for i in r:
        output_matrix = np.concatenate((output_matrix, input_vector ** i), axis = 0)
        
    # Return the output_matrxi by reshaping and trasposing so that resulting
    # matrix has dimensions (Number of elements in input x N)
    return output_matrix.reshape(N, input_vector.shape[0]).T  



In [52]:
# Tescase1: calculate vandermonde_matrix with N = 3 increasing = False
x = np.array([1, 2, 3, 5])
output = vandermonde_matrix(x, 3)
print(output)

[[ 1.  1.  1.]
 [ 4.  2.  1.]
 [ 9.  3.  1.]
 [25.  5.  1.]]


In [53]:
# Tescase2: calculate vandermonde_matrix with N=4 increasing = True
x = np.array([3, -2, 12, 5, 8, 19])
output = vandermonde_matrix(x, 3, increasing=True)
print(output)

[[  1.   3.   9.]
 [  1.  -2.   4.]
 [  1.  12. 144.]
 [  1.   5.  25.]
 [  1.   8.  64.]
 [  1.  19. 361.]]


In [54]:
# Tescase3: calculate vandermonde_matrix with N = None increasing = False
x = np.array([1, 2, 3, 5])
output = vandermonde_matrix(x)
print(output)

[[  1.   1.   1.   1.]
 [  8.   4.   2.   1.]
 [ 27.   9.   3.   1.]
 [125.  25.   5.   1.]]
